name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: 設置 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 根據您的 Node.js 版本需求調整

      # Step 3: 安裝依賴
      - name: Install Dependencies
        run: npm install

      # Step 4: 部署到 AWS Lambda
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy with Serverless
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          REDIRECT: ${{ secrets.REDIRECT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REGION: ${{ secrets.REGION }}
        run: serverless deploy